const SUCCESS = '_SUCCESS';
const ERROR = '_ERROR';

export const GET_SHUFFLED_DECK = 'GET_SHUFFLED_DECK';
export const GET_SHUFFLED_DECK_SUCCESS = GET_SHUFFLED_DECK + SUCCESS;
export const GET_SHUFFLED_DECK_ERROR = GET_SHUFFLED_DECK + ERROR;

export const GET_CARDS = 'GET_CARDS';
export const GET_CARDS_SUCCESS = GET_CARDS + SUCCESS;
export const GET_CARDS_ERROR = GET_CARDS + ERROR;
